### ISSUE TITLE
Possibility to combine or calculated values for MQTT output

### ISSUE THREAD

**Issue by hubecker** [micw/homedatabroker#12]
I like combine or caclulate some values for MQTT output.
For example values from tibberpulse:

      - source: pulse.currentL1
        topic: TibberPulse/currentL1
      - source: pulse.currentL2
        topic: TibberPulse/currentL2
      - source: pulse.currentL3
        topic: TibberPulse/currentL3

combined into currents like this:

example: [1.2,2.3,-2.1]

      - source:  [<pulse.currentL1>,<currentL2>,<currentL3>]
        topic: openWB/set/counter/0/get/currents 

or 
      - source: pulse.powerTotal
        topic: TibberPulse/powerTotal

      - source: pulse.powerTotal / 1000 kW
        topic: TibberPulse/powerTotal

pulse.powerTotal in W  output kW with unit

Another question, can i use type: openmetrics to handle http/https api as output and would it be possible to generalise  the tibber-pulse-http as a more common http input to also use for example the [tibber api](https://developer.tibber.com/docs/guides/calling-api) or  [traccar api ](https://www.traccar.org/api-reference/#tag/Server) or others.

Thanks for our answer and this great broker.

Regards

Hubert

**Comment by micw** [comment]
Funny, I have imnplemented this in a basic fashion a few weeks ago. Have a look into https://github.com/micw/homedatabroker/blob/master/src/main/java/de/wyraz/homedatabroker/source/AggregationSource.java in master.

Here's a config example where I sum my 3 phases:

```
    - type: aggregation
      id: aggregate
      cron: '*/1 * * * * *'
      metrics:
      - id: gridPowerTotal
        unit: W
        aggregation: sum
        inputMetrics:
        - victron.gridPowerL1
        - victron.gridPowerL2
        - victron.gridPowerL3
```

Currenly only "sum" is implemented but I can add other aggregations on interest.

Your 2nd example would require some kind of expression parser. Doable (I already implemented a few in my past) but I'd add it only if necessary. For the particular example I'd rather add better support for Units (e.g. if you sum kWh and Wh, conversion could be done automatically).

Openmetrics does support http and https, I use it to feed into victoriametrics.

For a generic http input please create another ticket to collect the ideas. I have the feeling that this could become quite feature-rich :-)
